name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Run tests

      run: python -m unittest discover

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/accents-telegram-bot:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    env:
      PROJECT_DIRECTORY: "/projects/Accents"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Commands to stop and remove the container
            docker stop accents || true
            docker rm accents || true

            # Pull the Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/accents-telegram-bot:latest

            # Define Mounts
            mount_logs="--mount type=bind,source="$(pwd)"/logs,target=${{ env.PROJECT_DIRECTORY }}/logs"
            mount_options="${mount_logs}"

            # Run Docker container
            docker run -d -p 80:80 --name accents $mount_options -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} ${{ secrets.DOCKERHUB_USERNAME }}/accents-telegram-bot:latest
